In [11]:
#创建数组
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print(a.dtype)
print(a.shape)
print(b.shape)

int32
(3,)
(2, 3)


In [19]:
#结构数组
"""定义结构类型，结构中的字段占用连续的内存空间，每个结构体占用的内存大小相同"""
import numpy as np
persontype = np.dtype({
    'names' : ['name','age','chinese','math','english'],
    'formats': ['S32','i','i','i','f']
})

peoples = np.array([("ZhangFei",32,75,100,90),("GuanYu",24,85,96,88.5)],dtype=persontype)
ages=peoples[:]['age']
print(ages)
print(np.mean(ages))

[32 24]
28.0


In [22]:
import numpy as np
booktype=np.dtype({
    'names':['name','author','type'],
    'formats':['S32','S32','S32']
})
books = np.array([("One day",'Jack','love story'),("Love you like love life",'Rose','love story')],dtype = booktype)
print(books[:]['name'])

[b'One day' b'Love you like love life']


In [30]:
#连续数组的创建
x1 = np.arange(1,11,2)#指定 初始值、终值、步长 （默认不包括终值）
print(x1)
x2 = np.linspace(1,9,5)#指定 初始值、终值、元素个数 （默认包括终值）
print(x2)

#算数运算
print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.remainder(x1,x2))


[1 3 5 7 9]
[1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [35]:
#统计函数
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8.9]])
print(np.amin(a))
print(np.amin(a,0))


[1, 2, 3]
[1, 2, 3]
